# （1）Crate A and X matrix


In [47]:
import pandas as pd
import numpy as np

OD=pd.read_csv('D:\\GNN\\OCD\\OD_pd.csv')

In [48]:
OD

Unnamed: 0             O             D  flow  O_id  D_id
0               0  270539800001  270539800001  7145  1485  1485
1               1  270530269092  270530269092  3311  1159  1159
2               2  270530251002  270530251002  2371   861   861
3               3  271390803011  271390803011  2347  1904  1904
4               4  270530267105  270530267105  1928  1072  1072
...           ...           ...           ...   ...   ...   ...
14159       14159  271230425014  271230424024    11  1860  1856
14160       14160  270370607501  270370607212    11   420   365
14161       14161  270370607342  270370607312    11   390   381
14162       14162  270531069002  270531108002    11  1344  1422
14163       14163  270030508072  270030507061    11   148   118

[14164 rows x 6 columns]

In [49]:
OD.query('O_id==2083')

Unnamed: 0             O             D  flow  O_id  D_id
314           314  271630714004  271630714004   224  2083  2083
2474         2474  271630714004  271630714003    53  2083  2082
3740         3740  271630714004  271630712092    37  2083  2076
3904         3904  271630714004  271630714002    36  2083  2081
5523         5523  271630714004  271630712061    27  2083  2066
6044         6044  271630714004  271630714005    25  2083  2084
10927       10927  271630714004  271630712083    14  2083  2074
11204       11204  271630714004  271630714001    14  2083  2080

In [50]:
m = n = 2085
Mat = [[0] * m] * n

In [52]:
Mat_np=np.array(Mat)

In [53]:
Mat_np

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [54]:
O=OD.iloc[1,:]['O_id']
O

1159

In [55]:
for i in range(len(OD)):
    O=OD.iloc[i,:]['O_id']
    D=OD.iloc[i,:]['D_id']
    Mat_np[O,D]=OD.iloc[i,:]['flow']
    if(Mat_np[O,D]>5000):
        print(Mat_np[O,D])


7145


In [56]:
Mat_np[0,1]

67

In [57]:
# Diag is zero
row, col = np.diag_indices_from(Mat_np)
Mat_np[row,col] = 0

In [58]:
Mat_np[0,0]

0

In [59]:
m = n = 2085
Mat_sym = [[0] * m] * n
Mat_sym=np.array(Mat_sym)

for i in range(2085):
    for j in range(2085):
        Mat_sym[i,j]=Mat_np[i,j]+Mat_np[j,i]
        

In [60]:
Mat_sym

array([[  0, 134, 233, ...,   0,   0,   0],
       [134,   0, 288, ...,   0,   0,   0],
       [233, 288,   0, ...,   0,   0,   0],
       ...,
       [  0,   0,   0, ...,   0,  75,  11],
       [  0,   0,   0, ...,  75,   0,  63],
       [  0,   0,   0, ...,  11,  63,   0]])

In [61]:
from scipy.sparse import csr_matrix

# convert to sparse matrix representation 
A = csr_matrix(Mat_sym)
print("Sparse matrix: \n",A)

Sparse matrix: 
   (0, 1)	134
  (0, 2)	233
  (0, 12)	55
  (0, 15)	43
  (0, 18)	11
  (0, 20)	14
  (1, 0)	134
  (1, 2)	288
  (1, 3)	52
  (1, 12)	24
  (1, 13)	58
  (1, 14)	47
  (1, 15)	138
  (2, 0)	233
  (2, 1)	288
  (2, 12)	15
  (2, 13)	15
  (2, 15)	56
  (3, 1)	52
  (3, 4)	31
  (3, 5)	13
  (3, 14)	12
  (4, 3)	31
  (4, 5)	11
  (4, 6)	72
  :	:
  (2081, 2084)	89
  (2082, 2070)	21
  (2082, 2073)	13
  (2082, 2076)	56
  (2082, 2078)	31
  (2082, 2081)	17
  (2082, 2083)	75
  (2082, 2084)	11
  (2083, 2066)	45
  (2083, 2072)	12
  (2083, 2074)	33
  (2083, 2076)	99
  (2083, 2080)	33
  (2083, 2081)	99
  (2083, 2082)	75
  (2083, 2084)	63
  (2084, 2066)	71
  (2084, 2067)	16
  (2084, 2074)	68
  (2084, 2076)	18
  (2084, 2079)	18
  (2084, 2080)	56
  (2084, 2081)	89
  (2084, 2082)	11
  (2084, 2083)	63


In [62]:
m = 1
n=2085
X = [[1] * m] * n

X_np=np.array(X)

X = csr_matrix(X_np)
print("Sparse matrix: \n",X)

Sparse matrix: 
   (0, 0)	1
  (1, 0)	1
  (2, 0)	1
  (3, 0)	1
  (4, 0)	1
  (5, 0)	1
  (6, 0)	1
  (7, 0)	1
  (8, 0)	1
  (9, 0)	1
  (10, 0)	1
  (11, 0)	1
  (12, 0)	1
  (13, 0)	1
  (14, 0)	1
  (15, 0)	1
  (16, 0)	1
  (17, 0)	1
  (18, 0)	1
  (19, 0)	1
  (20, 0)	1
  (21, 0)	1
  (22, 0)	1
  (23, 0)	1
  (24, 0)	1
  :	:
  (2060, 0)	1
  (2061, 0)	1
  (2062, 0)	1
  (2063, 0)	1
  (2064, 0)	1
  (2065, 0)	1
  (2066, 0)	1
  (2067, 0)	1
  (2068, 0)	1
  (2069, 0)	1
  (2070, 0)	1
  (2071, 0)	1
  (2072, 0)	1
  (2073, 0)	1
  (2074, 0)	1
  (2075, 0)	1
  (2076, 0)	1
  (2077, 0)	1
  (2078, 0)	1
  (2079, 0)	1
  (2080, 0)	1
  (2081, 0)	1
  (2082, 0)	1
  (2083, 0)	1
  (2084, 0)	1


In [63]:
from scipy import sparse


sparse.save_npz('D:/GNN/overlapping-community-detection-master/A_0526.npz', A)  #保存
sparse.save_npz('D:/GNN/overlapping-community-detection-master/X_0526.npz', X)  #保存

#csr_matrix_variable = sparse.load_npz('path.npz') #读



In [66]:
A.todense()

matrix([[  0, 134, 233, ...,   0,   0,   0],
        [134,   0, 288, ...,   0,   0,   0],
        [233, 288,   0, ...,   0,   0,   0],
        ...,
        [  0,   0,   0, ...,   0,  75,  11],
        [  0,   0,   0, ...,  75,   0,  63],
        [  0,   0,   0, ...,  11,  63,   0]], dtype=int32)

In [67]:
A_non_sym = csr_matrix(Mat_np)


A_non_sym.todense()

sparse.save_npz('D:/GNN/overlapping-community-detection-master/A_non_sym.npz', A_non_sym)  #保存


In [68]:
A_non_sym.todense()

matrix([[  0,  67, 117, ...,   0,   0,   0],
        [ 67,   0, 141, ...,   0,   0,   0],
        [116, 147,   0, ...,   0,   0,   0],
        ...,
        [  0,   0,   0, ...,   0,  22,   0],
        [  0,   0,   0, ...,  53,   0,  25],
        [  0,   0,   0, ...,  11,  38,   0]], dtype=int32)

# Train the Overlapping GCN model

In [51]:
import os

os.chdir('D:/GNN/overlapping-community-detection-master/')#更改路径，''里面为更改的路径

import nocd
import matplotlib.pyplot as plt
import numpy as np
import scipy.sparse as sp
import torch
import torch.nn as nn
import torch.nn.functional as F

from sklearn.preprocessing import normalize


%matplotlib inline

torch.set_default_tensor_type(torch.cuda.FloatTensor)

Define the hyperparameters

In [54]:
hidden_sizes = [128]    # hidden sizes of the GNN
weight_decay = 1e-2     # strength of L2 regularization on GNN weights
dropout = 0.5           # whether to use dropout
batch_norm = True       # whether to use batch norm
lr = 1e-3               # learning rate
max_epochs = 500        # number of epochs to train
display_step = 25       # how often to compute validation loss
balance_loss = True     # whether to use balanced loss
stochastic_loss = True  # whether to use stochastic or full-batch training
batch_size = 20000      # batch size (only for stochastic training)

Select & normalize the feature matrix

For some datasets where the features are very informative / correlated with the community structure it's better to use `X` as input (e.g. co-authorship networks w/ keywords as node features). Otherwise, you should try using `A` or `[A, X]` as input.

In [55]:
x_norm = normalize(X)  # node features
# x_norm = normalize(A)  # adjacency matrix
# x_norm = sp.hstack([normalize(X), normalize(A)])  # concatenate A and X
x_norm = nocd.utils.to_sparse_tensor(x_norm).cuda()

Define the GNN model

In [56]:
N=X.shape[0]
K=50

sampler = nocd.sampler.get_edge_sampler(A, batch_size, batch_size, num_workers=5)
gnn = nocd.nn.GCN(x_norm.shape[1], hidden_sizes, K, batch_norm=batch_norm, dropout=dropout).cuda()
adj_norm = gnn.normalize_adj(A)
decoder = nocd.nn.BerpoDecoder(N, A.nnz, balance_loss=balance_loss)
opt = torch.optim.Adam(gnn.parameters(), lr=lr)

In [ ]:
val_loss = np.inf
validation_fn = lambda: val_loss
early_stopping = nocd.train.NoImprovementStopping(validation_fn, patience=10)
model_saver = nocd.train.ModelSaver(gnn)


for epoch, batch in enumerate(sampler):
    if epoch > max_epochs:
        break
    if epoch % 2 == 0:
        localtime = time.asctime( time.localtime(time.time()) )
        print(localtime)
        with torch.no_grad():
            gnn.eval()
            # Compute validation loss
            Z = F.relu(gnn(x_norm, adj_norm))
            val_loss = decoder.loss_full(Z, A)
            #print(f'Epoch {epoch:4d}, loss.full = {val_loss:.4f}, nmi = {get_nmi():.2f}')
            
            # Check if it's time for early stopping / to save the model
            early_stopping.next_step()
            if early_stopping.should_save():
                model_saver.save()
            if early_stopping.should_stop():
                print(f'Breaking due to early stopping at epoch {epoch}')
                break
            
    # Training step
    gnn.train()
    opt.zero_grad()
    Z = F.relu(gnn(x_norm, adj_norm))
    ones_idx, zeros_idx = batch
    if stochastic_loss:
        loss = decoder.loss_batch(Z, ones_idx, zeros_idx)
    else:
        loss = decoder.loss_full(Z, A)
    loss += nocd.utils.l2_reg_loss(gnn, scale=weight_decay)
    loss.backward()
    opt.step()

In [ ]:
print(AS)